name: Hiatus
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18025
title: Hiatus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e7e7'
    - '#1a1a1a'
    - '#cacaca'
    - '#a5a5a5'
    - '#6a6a6a'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
